name: Build Docker Image

on:
  push:
    branches:
      - main
env:
  GCP_PROJECT_ID: "global-axe-391317"
  GCR_LOGIN_URL: "https://us.gcr.io"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'use gcloud cli'
        shell : bash
        run: |
          gcloud info
          echo "==============================================="
          gcloud config set project ${{env.GCP_PROJECT_ID}}
          echo "==============================================="
          gcloud info
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: global-axe-391317
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true
          install_app_engine: true
          install_kubectl: true
          install_beta_components: true
      - name: Authenticate using gcloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
        run: gcloud auth application-default login --quiet --password-file-stdin < password.txt
      - name: Build Docker image
        run: |- 
          docker build -t your-docker-image:latest -f images/Dockerfile .
          docker images
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Docker Image
          path: .
          retention-days: 7
